default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: saans_studio_development

test:
  <<: *default
  database: saans_studio_test

production:
  <<: *default
  database: susurrus_production
  password: <%= ENV['SAANS_STUDIO_DATABASE_PASSWORD'] %>
