default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  charset: utf8mb4_unicode_ci
  username: root
  password:
  socket: /tmp/mysql.sock
  port: 3306

development:
  <<: *default
  database: saans_studio_development

test:
  <<: *default
  database: saans_studio_test

production:
  host: 127.0.0.1
  <<: *default
  database: susurrus_production
  password: <%= ENV['SAANS_STUDIO_DATABASE_PASSWORD'] %>
